services:
  website:
    image: joseluisq/static-web-server:2-alpine
    container_name: website
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/srv
      - SERVER_CONFIG_FILE=/etc/config.toml
    volumes:
      - ./site:/srv
      - ./config/config.toml:/etc/config.toml
    networks:
      - proxy

networks:
  proxy:
    external: true